name: E2E tests

on:
  push:
  pull_request:
    branches: [ "master" ]
  schedule:
    - cron: '0 12 * * 6'
  workflow_dispatch:

jobs:
  test-popup:
    strategy:
      fail-fast: false
      matrix:
        browser: [chrome, firefox]
        os: [ubuntu-latest, windows-latest, macos-latest]

        exclude:
          - os: ${{ (github.event_name == 'schedule' || github.event_name == 'workflow_dispatch') && 'dummy' || 'windows-latest' }}
          - os: ${{ (github.event_name == 'schedule' || github.event_name == 'workflow_dispatch') && 'dummy' || 'macos-latest' }}

    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout the repo
        uses: actions/checkout@v3

      - uses: cypress-io/github-action@v6
        with:
          build: npm run build
          start: npm run popup:serve
          start-windows: npm run popup:serve
          browser: ${{ matrix.browser }}
          wait-on: 'http://localhost:8000'
          wait-on-timeout: 30
          headed: true
